version: '3.4'

services:
  sio.translationoption.importer:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Store=Server=sio.sql.store;Initial Catalog=sio-store;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__Projection=Server=sio.translationoption.importer.sql.projections;Initial Catalog=sio-translationoption-importer-projections;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__RabbitMq=amqp://guest:guest@sio.rabbitmq
      - RabbitMq__Exchange=sio-docker
      - RabbitMq__ManagementApi__Endpoint=http://localhost:15672
      - RabbitMq__ManagementApi__User=guest
      - RabbitMq__ManagementApi__Password=guest
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sio.translationoption.importer.sql.projections:
    user: 'root'
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1451:1433"
    volumes:
      - /var/opt/mssql/data